name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Verify Build Folder
        run: ls -lah ./build  # Ensure build folder exists

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2  # Updated to v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Build Files to S3
        run: |
          aws s3 sync ./build s3://shivani-projects --delete
